### ISSUE TITLE
\node_modules\ng2-cache\ng2-cache.ts is missing from the TypeScript compilation.

### ISSUE THREAD

**Issue by se02951** [Jackson88/ng2-cache#21]
Hi team,

I got problem like that.
ERROR in ./node_modules/ng2-cache/ng2-cache.ts
Module build failed: Error: C:\Users\Gildarts\Desktop\Cache\login-test\node_modules\ng2-cache\ng2-cache.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open
an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\Users\Gildarts\Desktop\Cache\login-test\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:674:23)
    at plugin.done.then (C:\Users\Gildarts\Desktop\Cache\login-test\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)

**Comment by shivam25** [comment]
Having the same issue. Tried with 2-3 different versions of angular but still the problem exists.
![image](https://user-images.githubusercontent.com/4638586/37448420-4aefd352-284c-11e8-9885-5f96f3a29f69.png)

**Comment by paritosh64ce** [comment]
Getting same issue. Any updates?

**Comment by paritosh64ce** [comment]
Solved this by introducing `ng2-cache.ts` file inside `tsconfig.json`'s `include`  section.

    "include": [
      "src/**/*",
      "node_modules/ng2-cache/ng2-cache.ts"
    ]

You may close this issue if it solves your problem.

**Comment by paritosh64ce** [comment]
Could you close this issue if its fixed with this PR and the updated npm package (v 0.2.0)?
